/*
 * AUSF API
 *
 * OpenAPI specification for AUSF
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UeAuthenticationCtx struct {

	AuthType *AuthType `json:"authType"`

	Var5gAuthData *OneOfAv5gAkastring `json:"5gAuthData"`

	Links map[string]LinksValueSchema `json:"_links"`

	ServingNetworkName string `json:"servingNetworkName,omitempty"`
}
