/*
 * AUSF API
 *
 * OpenAPI specification for AUSF
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/nausf-auth/v1/",
		Index,
	},

	{
		"EapAuthMethod",
		strings.ToUpper("Post"),
		"/nausf-auth/v1/ue-authentications/{authCtxId}/eap-session",
		EapAuthMethod,
	},

	{
		"UeAuthenticationsAuthCtxId5gAkaConfirmationPut",
		strings.ToUpper("Put"),
		"/nausf-auth/v1/ue-authentications/{authCtxId}/5g-aka-confirmation",
		UeAuthenticationsAuthCtxId5gAkaConfirmationPut,
	},

	{
		"UeAuthenticationsPost",
		strings.ToUpper("Post"),
		"/nausf-auth/v1/ue-authentications",
		UeAuthenticationsPost,
	},
}
